version: '3'

services:
  backend:
    build: .
    ports:
      - 4000:4000
    environment:
      - DB_USER=postgres
      - DB_PASS=1234
      - DB_NAME=db_marinke
      - DB_HOST=db
    volumes:
      - .:/app-backend
    container_name: meliponicultor-api
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=1234
    restart: always
